### ISSUE TITLE
Modificar manejo de paths absolutos de archivos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#1]
* Usando __file__
* Cuidando cross-platform del separador (os.path.join() para todo)

**Comment by capitantoto** [comment]
No estoy seguro a que te referís con "Usando **file**", pero en resumidas cuentas, ahora esto anda gracias a las siguientes modificaciones:
- Se agregó una constante al módulo, `ABSOLUTE_LIBRARY_PATH = path.dirname(path.abspath(__file__))`
- La `base_uri` para el RefResolver se genera como `base_uri=urljoin('file:', schema_path)`

Los cambios se encuentran en la branch `path-issues`, que ya pasa el build en Travis.

**Comment by capitantoto** [comment]
En python 3, la librería `urlparse` se llama `urllib.parse`: en consecuencia, el build en linu py3.5 está roto. Nos calienta?

**Comment by abenassi** [comment]
Gonza, en principio *no nos importa* que el build se rompa en 3.5 (es un
nice-to-have en este punto, pero nos va a importar en el futuro) pero si no
te distrae de las prioridades y querés ir viendo que el código empiece a
ser bilingüe, sos libre de hacerlo.

2016-11-29 14:49 GMT-03:00 Gonzalo Barrera Borla <notifications@github.com>:

**Comment by capitantoto** [comment]
Resuelto en https://github.com/datosgobar/pydatajson/pull/4
