### ISSUE TITLE
Modificar el schema de validación para que incluya validación de tipos complejos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#10]

**Comment by capitantoto** [comment]
Esto está casi terminado, así que voy a documentar las decisiones ejecutivas que requirió:

- Se modificó el tipo mixto "stringOrNull" para ser "nonEmptyStringOrNull", y- Se agregó el tipo mixto "nonEmptyString". Salvo que por reglas adicionales no sea necesario validar la longitud mínima de una string, no hay ninguna versión "simple" del tipo "string": todas son "nonEmptyString" (para los campos obligatorios) o "nonEmptyStringOrNull" (para los campos opcionales)

(continuará)
