### ISSUE TITLE
Agregar opción para copiar el `identifier` original, sin prependear el `catalog_id`

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#103]
**Contexto**

Poder escribir un dataset con su identifier original es útil para utilizar la función no como federador, sino como forma de restaurar los metadatos de un dataset a partir de un backup anterior.

**Propuesta**

Agregar un argumento opcional `prepend_catalog_identifier = True` que indica si debe o no _prependearse_ el identificador de un catálogo al identificar del dataset que se desea escribir en CKAN.

**Comment by poligarcia** [comment]
@abenassi puede ser que quedó incompleto el issue?

**Comment by abenassi** [comment]
@poligarcia sí! Ahí completo :-)
