### ISSUE TITLE
Fijar un piso de 80% de test coverage y agregar el chequeo al build de Travis

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#112]
**Contexto**

`pydatajson` es uno de los proyectos de código abierto que como _librería funcional_ consideramos un producto prolijo y acabado.

El código en este repositorio tiene que estar bien documentado, bien testeado y seguir estándares de estilo.

**Propuesta**

Vamos a formalizar el abordaje de estos aspectos de a poco, de manera que incorporemos al build de Travis algunas de estas reglas.

**Segundo:** empezar incorporando un piso de 80% de test coverage para aceptar un build en Travis.

Tener en cuenta que el objetivo de mediano plazo va a ser levantar esta vara al 90%, pero por ahora empezamos por un 80%.

**Comment by poligarcia** [comment]
`pytest` [dice que](https://travis-ci.org/datosgobar/pydatajson/jobs/408231097#L714) el coverage es del *81%*. Quizás coveralls está tomando otra base o alguna configuración que no tenemos en cuenta en coverage.

Primero busquemos que esos dos números coincidan y a partir de ahí subimos de a poco la cobertura.

**Comment by abenassi** [comment]
Ok! Cuando hice este issue fue hace mucho tiempo.. tal vez se hicieron
muchos más tests en el camino. En todo caso aprovechémoslo para fijarnos si
hay que subir un poco más la vara a un % mayor.
