### ISSUE TITLE
Incorpora la posibilidad de validar contra un esquema de condiciones mínimas y contra otro de condiciones máximas

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#12]
* Definir condiciones mínimas con @abenassi y con @fpetrone
* Definir condiciones máximas con @abenassi y con @fpetrone
* Ver cómo sería levantar warnings para el caso de campos extras que no están en el perfil de metadatos

**Comment by capitantoto** [comment]
@abenassi pretendemos hacer algo con respecto a esto para la v0.2? O finalmente no?

**Comment by capitantoto** [comment]
El día que se ataque este problema, sería útil revisar cuán estrictas son las validaciones que realizamos, y si efectivamente estamos haciendo todas las que deseamos y ninguna más. En particular, habría uqe especificar en algún lugar de la documentación el tratamiento de los campos "nulos/str vacías"

**Comment by abenassi** [comment]
Por ahora esto está fuera de agenda.
