### ISSUE TITLE
Wrappers para push_dataset_to_ckan()

### ISSUE THREAD

**Issue by lrromero** [datosgobar/pydatajson#128]
El objetivo sería implementar wrappers que resumen formas de utilizar la función `push_dataset_to_ckan()` muy comunes o con cierta especificidad, usando los parámetros opcionales de la función o iterándola.

- [x] `restore_dataset_to_ckan()`: restaura un dataset con su metadata *idéntica*, de un data.json a un CKAN.
- [x] `harvest_dataset_to_ckan()`: federa un dataset de un nodo original (data.json) a uno indexador (CKAN), transformando algunos campos de metadatos en el camino.
- [ ] `restore_catalog_to_ckan()`: tiene un parámetro opcional que es un array de identifiers de datasets, para itera la función `restore_dataset_to_ckan()`. Si es `None` esta función restaura *todos* los datasets del catálogo.
- [x] `harvest_catalog_to_ckan()`: tiene un parámetro opcional que es un array de identifiers de datasets, para itera la función `harvest_dataset_to_ckan()`. Si es `None` esta función federa *todos* los datasets del catálogo.

**Comment by abenassi** [comment]
@lrromero fijate que ahí modifiqué la descripción del issue para incluir otros dos wrappers útiles, tanto para usar la función desde un Jupyter cualquiera como para cuando la integres en `monitoreo-apertura`.

**Comment by lrromero** [comment]
Como cada dataset en CKAN requiere una organización a la cual pertenecer, la función `restore_catalog_to_ckan()` necesita lógica más compleja que los otros wrappers. Separo ese método en particular para el issue #140.
