### ISSUE TITLE
Permitir diccionarios ya deserializados como input, además de .jsons

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#13]
* Cambiar nombre al método auxiliar _deserialize_json()

**Comment by capitantoto** [comment]
Esto fue realizado a través de una segunda función estática, `_to_dict`, que acepta un diccionario o una string, y:
* si recibe un diccionario, lo devuelve intacto, y
* si recibe una string, se la pasa a `_deserialize_json` para que la convierta en un diccionario
