### ISSUE TITLE
Robustecer el manejo de themes por parte de push_dataset_to_ckan()

### ISSUE THREAD

**Issue by lrromero** [datosgobar/pydatajson#130]
Este es un issue que hace referencia al 24 de monitoreo apertura:
https://github.com/datosgobar/monitoreo-apertura/issues/24
Lo abro acá porque me parece que es más apropiado discutirlo en este repo.

--------------------------------------------------------------------------------------------------
**Contexto**

Se intentó federar el dataset de series de tiempo a la instancia andino.datos.gob.ar, de la siguiente manera:
```
catalog_modernizacion = DataJson("http://infra.datos.gob.ar/catalog/modernizacion/data.json")

catalog_modernizacion.push_dataset_to_ckan(
    "modernizacion", "ministerio-de-modernizacion", "7",
    portal_url, apikey
)
```
y dio la rta:
```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-8-b4c2dae3c9ec> in <module>()
      1 catalog_modernizacion.push_dataset_to_ckan(
      2     "modernizacion", "ministerio-de-modernizacion", "7",
----> 3     portal_url, apikey
      4 )

/Users/abenassi/github/pydatajson/pydatajson/federation.pyc in push_dataset_to_ckan(catalog, catalog_id, owner_org, dataset_origin_identifier, portal_url, apikey)
     49         theme_taxonomy = catalog.themes
     50         for theme in themes:
---> 51             label = next(x['label'] for x in theme_taxonomy if x['id'] == theme)
     52             package['tags'].append({'name': label})
     53 

StopIteration: 
```

**Propuesta**

Investigar qué hizo que se frenara la operación. Puede ser que el problema sea que se requiere crear "temas" que la instancia destino no tiene. Si es así, lo mejor sería incorporar la creación automática de temas que no existan dentro de la operación de federación.

**Comment by lrromero** [comment]
@abenassi Este issue plantea 3 problemas que me parece interesante discutir:

a- El problema venía por  el lado de los ids de `theme`. En el `theme_taxonomy` están en minúsculas y en el dataset en mayúsculas. Probé con la función `search.get_theme()`, pero también es case sensitive. ¿Cuál sería la mejor forma de avanzar? Hacer case insensitive `get_theme()` o mantenerla así y tomar el caso en `push-dataset()`?

b- Una vez resuelto el tema de los ids, la federación va a seguir fallando porque el label del tema 'Agroganadería, pesca y forestación' tiene coma (que está permitido). Pero el keyword no las permite, habría que transformar los labels para que sean válidos? 

c- Lo que mencionaste de los temas que inexistentes es como decís, `push_dataset()` no los crea. Fue una decisión tomada porque: Si estás federando, los temas son los super temas del dataset y el nodo federador debería tenerlos. Si estás restaurando, los temas ya deberían estar en la taxonomía.
Si hay un caso en el cual el catálogo de destino no tiene un tema de un dataset federado, por el momento se ignora y no aparece en el dataset. ¿Es posible que se de ese caso?

¿Qué opiniones tenés al respecto?

**Comment by poligarcia** [comment]
Con respecto al punto b) lo que podemos hacer @abenassi es reemplazar las comas (y los caracteres no permitidos) por un caracter vacío. Esto hace que la operación no sea reversible, es decir, no podemos transformar keywords en labels (desconozco si es necesario).

Los caracteres permitidos para keywords, según la documentación de CKAN (tenés el link por ahí @lrromero?) son caracteres alfanuméricos (incluyendo caracteres acentuados), *.*, *-* y *_*.
Deberíamos reemplazar todos los caracteres que no estén en ese subconjunto.

**Comment by abenassi** [comment]
@lrromero  te respondo a cada uno!

a) "Hacer case insensitive get_theme()" me parece la opción correcta. Este
es el método que retiene la responsabilidad de saber que los ids de los
themes son case-insensitive desde el punto de vista de nuestra convención.

b) Esto es nuevo para mí. Eliminemos los caracteres prohibidos y dejamos
sólo el espacio.

c) Lucas, tu razonamiento es válido. Puede ser un poco riesgoso que la
operación de federación cree temas porque sí, tal vez.... Pero tengo 2
objeciones:

1. No podemos simplemente ignorar el tema original si estamos restaurando
un dataset, y dejar pasar el dataset silenciosamente... debería fallar.
Porque no estamos siendo fieles a los metadatos.
2. También  es bastante fiaca restaurar un catálogo si hay que crear
manualmente los themes de vuelta...

Solución: agreguemos a pydatajson los metodos 'push_theme_to_ckan()' y el
wrapper 'push_themes_to_ckan()'

Les parece?

**Comment by abenassi** [comment]
De paso: los wrappers a nivel de catálogo que les agregué al issue #128
usarían el método  'push_themes_to_ckan()'  para crear todos los themes
necesarios para federar o restaurar el catálogo de referencia.

Así se hace mucho más fácil la operación, y además es el contexto adecuado
donde uno crearía themes (el de nivel "catálogo", en lugar del de nivel
"dataset").

**Comment by lrromero** [comment]
@poligarcia Es como decís: punto, guión y guión bajo.
http://docs.ckan.org/en/latest/api/#ckan.logic.action.create.tag_create (Ignorando la parte de vocabulary_id porque los tags los pasamos adentro del package)

@abenassi 
Me parece bien la idea de `push_theme_to_ckan()`. Creo que estaría bueno encararlo por un issue separado y dejar en el scope de este issue el punto a y b. Te parece?

**Comment by abenassi** [comment]
@lrromero sí totalmente! Agregalo nomás a la lista, junto en prioridad con
el de los wrappers :-)

2018-03-15 15:21 GMT-03:00 lrromero <notifications@github.com>:
