### ISSUE TITLE
Refactorizar validate_catalog() para que use iter_errors() solamente, en lugar de jsonschema.ErrorTree()

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#15]

**Comment by capitantoto** [comment]
Resuelto! Básicamente:
1. Volvemos al esquema original, donde se define una respuesta por default si no hay errores, y se va actualizando en funcion de los errores encontrados.
2. Dado el `path` de un error en el catálogo validado, la regla de decisión para asignarlo a un cierto dataset o al catálogo es la siguiente:
  * Si el primer valor de `path` (que es una lista ordenada de claves del catálogo) es "dataset", y `path` tiene longitud mayor o igual a 2, el error corresponde al dataset con índice igual al segundo valor de `path`,
  * En cualquier otro caso, el error es a nivel catálogo.
