### ISSUE TITLE
Robustecer interpretación de listas a partir de strings separados por comas, en el reader de XLSX

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#162]
**Contexto**

La lectura de catálogos en XLSX se basa en distintas estrategias para leer aquellos campos que son listas (en el XLSX se representan como strings).

En el caso de que la lista se lea como "valores separados por comas" a veces los usuarios ponen una coma de más, generando un último string vacío "" como valor en la lista.

**Propuesta**

Modificar la lectura de XLSX para que cuando parsea un string de valores separados por comas hacia una lista ignore los valores vacíos, evitando listas con valores vacíos.

**Notas**

Recordar hacer un nuevo micro release de pydatajson con esta modificación y actualizar la versión en monitoreo-apertura.

**Comment by abenassi** [comment]
@abenassi debe agregar ejemplo del SMN para ver el issue más claro

**Comment by poligarcia** [comment]
@abenassi podés mandarnos el ejemplo please?

**Comment by abenassi** [comment]
[image: Screenshot 2018-07-12 14.00.04.png]

**Comment by poligarcia** [comment]
@abenassi nos falta el screenshot aca!

**Comment by abenassi** [comment]
<img width="252" alt="screenshot 2018-07-12 14 00 04" src="https://user-images.githubusercontent.com/4405346/43265909-72a27486-90c0-11e8-9175-590f240d1510.png">


Parece que por mail no se puede cargar el screenshot!! Ahí va @poligarcia
