### ISSUE TITLE
No se está federando el campo de `distribution_type`

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#166]
El metadato `distribution_type` no está logrando ser federado a Andino. Esto puede ser una falta de la función de federación de pydatajson o puede ser una falta de Andino.

Cargo el issue acá pero tal vez haya que moverlo a Andino.

**Comment by abenassi** [comment]
@poligarcia te arrobo nomás por si este issue no es de pydatajson, y hay que moverlo a Andino. Pero no hay especial urgencia en abordarlo, sólo hay que tenerlo trackeado y asignarle una prioridad dentro de la semana que viene.

**Comment by lrromero** [comment]
@abenassi El issue pasa por pydatajson. El campo `type` se agregó en el perfil 1.1.1 y no actualizamos el mapeo de distribution a resource de CKAN. Sería cuestión de contemplarlo en `map_distributions_to_resources()`. 

Por otro lado, el campo es `distribution_type` o `type` solo?

**Comment by abenassi** [comment]
@lromero uso "distribution_type" como una forma de decir "el campo de
metadatos `type` de la clase `distribution`. Perfecto entonces, queda el
issue para actualizar el mapeo acá.

**Comment by abenassi** [comment]
@abenassi testear esto con 0.0.4
