### ISSUE TITLE
Incorpora métodos para generar un config file para harvester

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#17]
* Devuelve un mini-reporte en CSV de los datasets disponibles para harvestear en un data.json

* Toma el CSV mini-reporte donde se especifican los datasets a harvestear y genera un config file listo para el harvester

* Ofrece la opción de devolver un data.json filtrado por el CSV mini-reporte, en lugar de un config file para un harvester

**Comment by capitantoto** [comment]
* Devuelve un mini-reporte en CSV de los datasets disponibles para harvestear en un data.json **HECHO**

* Toma el CSV mini-reporte donde se especifican los datasets a harvestear y genera un config file listo para el harvester **HECHO**

* Ofrece la opción de devolver un data.json filtrado por el CSV mini-reporte, en lugar de un config file para un harvester **PENDIENTE**

Me gustaría hablar un poco sobre el tercer punto: el mockup del método que armamaos no me está proveyendo toda la info que necesito.
