### ISSUE TITLE
get_fields con only_time_series=True no devuelve todas las series de tiempo

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/pydatajson#177]
* ¿Cuál es el comportamiento que esperabas y cuál fue el comportamiento recibido? 
Trabajando bajo el catálogo de `sspm` (http://infra.datos.gob.ar/catalog/sspm/data.json), `data_json.get_fields(only_time_series=True)` debería devolver entre sus resultados el field de la serie con ID `142.1_TOTAL_2001_A_37`, que es una serie de tiempo válida. Sin embargo no es encontrada entre los resultados. Sí lo es cuando se busca sin el filtro `only_time_series`.
* ¿Cuáles son los pasos para reproducir el bug?
```
In [29]: from pydatajson import DataJson

In [30]: data_json = DataJson('http://infra.datos.gob.ar/catalog/sspm/data.json')

In [31]: list(filter(lambda x: x['id'] == '142.1_TOTAL_2001_A_37', data_json.get_fields()))
Out[31]: 
[{'distribution_identifier': '142.1',
  'description': 'Total con capitalizacion transitorios de los Recursos tributarios totales y por tributo. Valores anuales (Base 2001)',
  'title': 'total_con_capitalizacion_transitorios',
  'dataset_identifier': '142',
  'scrapingIdentifierCell': 'AE10',
  'units': 'Millones de pesos',
  'id': '142.1_TOTAL_2001_A_37',
  'scrapingDataStartCell': 'AE11'}]

In [32]: list(filter(lambda x: x['id'] == '142.1_TOTAL_2001_A_37', data_json.get_fields(only_time_series=True)))
Out[32]: []
```
* Detalles del contexto: ¿qué sistema operativo, qué versión de navegador estás usando, por ejemplo?
Ocurre en Ubuntu 16.04 y 18.04, tanto en shell como cuando se usa en programas más grandes que lo usan como dependencia. Ambos casos se corre en python 3.6.5

**Comment by lrromero** [comment]
El field no aparece porque `pydatajson` pide que tenga tipo "number" o "integer" (https://github.com/datosgobar/pydatajson/blob/master/pydatajson/time_series.py#L22) y el field no tiene campo `type`.

@abenassi 
El field es inválido o hay que trabajar la lógica por el lado de `field_is_time_series()`? Qué pensas?

**Comment by abenassi** [comment]
Lucas está ok entonces! Si el field no tiene campo type, no lo tomamos como
series de tiempo.

Esto cierra el issue confirmando que la definición implementada de serie en
pydatajson está ok.

**Comment by lrromero** [comment]
Genial, cierro el issue entonces.
