### ISSUE TITLE
El validador del catálogo arroja mensaje y locación erróneos cuando hay más de un error.

### ISSUE THREAD

**Issue by melikes** [datosgobar/pydatajson#178]
**Contexto**
Una funcionalidad usada frecuentemente es la generación de reportes que contengan errores sobre el catálogo.  Método: `dj.validate_catalog(...)`

**Comportamiento esperado**
Deberían mostrarse todos los errores presentes en el catálogo, sin repetirse.

**Comportamiento recibido**
Al consultar los errores de un catálogo, aparece un único error repetido tantas veces como cantidad de errores tenga el catálogo.

**Pasos para reproducirlo**
· Descargar de este issue _fake-data.json_
· Ejecutar las siguientes lineas de código
```
import pydatajson
import pandas as pd

catalogo_path = './fake-data.json'   
catalogo = DataJson(catalogo_path)
dj = DataJson(catalogo_path)

pd.DataFrame(dj.validate_catalog(catalogo, only_errors=True, fmt="list")["catalog"])
 ```
· Modificar _fake-data.json_ y repetir pasos.

**Screenshots**
Ejemplo con un error:
![178-un-error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6894e7ab4158001248dbfb/125516c66e82c728ace21e0d46b9c3c26e978de48afbad4cb61fbcd6395428792c07b7692ac7b670ec4623575e5a4daf150b0b15feac892aa2e03b748d0d19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bf8849c4ee3a23e0828e4b2c53.png)
Ejemplo con tres errores:
![178-tres-errores](https://user-images.githubusercontent.com/34164411/43223674-40c5051e-902a-11e8-865a-66cebb31b68e.png)

Adjunto _fake-data.json_ con extensión _txt_ por políticas de github: 
[fake-data.txt](https://github.com/datosgobar/pydatajson/files/2229290/fake-data.txt)

**Comment by abenassi** [comment]
@poligarcia @lrromero perdonen la inclusión por la ventana de esto, pero finalmente @melikes descubrió lo que pasaba con esto y es de importancia elevada, así que lo puse dps de la nueva migración de ids.
