### ISSUE TITLE
Crea un método que genera un reporte a partir de una lista de data.jsons

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#22]
* Campos harvester: catalog_metadata_url, dataset_title, dataset_accrualPeriodicity

* Campos especiales: valid_metadata, harvest

* Campos informativos: dataset_description, dataset_publisher_name, dataset_superTheme, dataset_theme, dataset_landingPage, distributions_title_downloadUrl, catalog_title, catalog_description

* Fallas de metadata a nivel de catálogo generan warnings

**Comment by capitantoto** [comment]
Hecho!
