### ISSUE TITLE
Cambiar nombre de las variables "datajson_path" a "catalog" o algo que sea más declarativo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#23]

**Comment by capitantoto** [comment]
Me gustaría que la filosofía de los métodos de DataJson sea la siguiente:
Los argumentos a los métodos se llamarán *según los elementos que manipulan*, y no según los *nombres de sus representaciones*, aunque efectivamente reciban una representación del elemento.
 Así, por ejemplo, validate_catalog() tendrá un argumento `catalog` (en lugar de `datajson_path_or_url`), que acepta una *representación* aceptable de un catálogo (un diccionario, o una str con un path a un archivo en formato JSON que describe un diccionario). 
Todo método de DataJson() que acepte un parámetro `catalog(s)`, deberá, como primer acción, transformar la representación externa del catálogo a una representación interna, en formato de diccionario.

Similarmente, si un método recibe un argumento `report`, el input deberá ser una representación externa de un reporte (es decir, un path a un CSV/XLSX o una lista de diccionarios), y lo primero que hace es transformar ese input a la represetación interna de un reporte (lista de diccionarios).

**Comment by capitantoto** [comment]
En general, debemos de revisar los nombres de todas las variables de la librería, para asegurarse de que todas sean mínimamente entendibles.
