### ISSUE TITLE
Rutear dominio de http://datos.jus.gob.ar

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#241]
Hoy no se puede leer desde los ambientes de monitoreo.

**Comment by cesarquilmes** [comment]
Nos comunicamos con personal del departamento IT de Justicia y nos confirmaron que la IP del servidor estaba bloqueada, segun nos comentan por "descargas masivas en intervalos regulares".
Verificamos que ya se puede acceder correctamente desde nuestra infraestructura.

**Comment by abenassi** [comment]
Les comentamos cómo es el patrón de descargas de nuestra infraestructura de monitoreo y desde qué IPs se hacen las conexiones.
