### ISSUE TITLE
Generar método intermedio que devuelva el reporte de datasets como objeto de python y no como reporte en un archivo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#25]

**Comment by capitantoto** [comment]
Finalmente, se decidió que los métodos que generan reportes devuelvan *siempre* un objeto de python, salvo que se les provea un argumento `export_path`, en cuyo caso devuelven `None`, y como efecto secundario exportan el reporte en formato CSV/XLSX via el método `_write()`.
