### ISSUE TITLE
Generar método intermedio que tome un reporte de datasets de python y lo exporte a un archivo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#26]
* Se lee el path del archivo para determinar si el reporte se genera como CSV o XLSX. Otros formatos raise Exception.

**Comment by capitantoto** [comment]
Este método está escrito (`_read()`, junto con `read_csv()` y `read_xlsx()`), con la siguiente salvedad:

 El objeto-reporte que estamos usando para comunicar entre metodos es una lista de diccionarios. Como los diccionarios no tienen sus claves ordenadas, al momento de escribir el reporte no podemos saber con seguridad en que orden quedarán sus columnas. Debemos decidir (a) en que orden esperamos que las columnas figuren en el reporte y en el config del harvester, y (b) cómo forzar al método _write a respetar dicho orden, que puede variar en función del objeto-reporte a ser escrito
