### ISSUE TITLE
Asegurar que pydatajson usa GMT-3 como default para federar o restaurar cuando interpreta una fecha, y que tiene un argumento para pasarle explícitamente el timezone a la función

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#274]

**Comment by AWolfsdorf** [comment]
Al ver un data.json en Andino, tiene que tener explicitado el timezone.Pero desde el lado de pydatajson en el pasado hemos visto que no pasa adecuadamente la fecha con un timezone explícito y el correcto
El tema es que no nos quedó un ejemplo claro y es difícil encontrar uno
La forma de probarlo, de todas maneras, sería armarte un caso de testeo donde pydatajson lee un catalogo en XLSX donde diga “2019-02-01” y a Andino esto tendría que llegar como “2019-02-01T00:00:00-03:00"
