### ISSUE TITLE
Integrar todos los métodos disponibles de lectura de un catálogo en el constructor de DataJson

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/pydatajson#42]
El constructor de DataJson() debe poder entender por sí mismo URLs simples (.JSON o .XLSX) para usar el lector de catálogo corrrespondiente, y tener un parámetro `format` que acepte "xlsx", "json" o "ckan" y fuerce el uso del lector correspondiente -en lugar de adivinar por la extensión-).

**Comment by abenassi** [comment]
Hay que chequear si esto ya es así o no.
