### ISSUE TITLE
Agregar los primeros tres indicadores

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/pydatajson#48]
Los primeros indicadores a implementar son:

* [x] Cantidad de datasets publicados (datasets_cant)
* [x] Cantidad de distribuciones publicadas (distribuciones_cant)
* [x] Datasets con metadata OK (distribuciones_meta_ok_cant)

La idea es armar la estructura de paquetes/clases que necesitamos para implementar todos los indicadores.

**Comment by lucaslavandeira** [comment]
También agregué los dos indicadores siguientes, datasets con metadata ERROR, porcentaje de datasets OK
