### ISSUE TITLE
Modificar la validación de URLs/URIs para ser un poco más tolerante con ciertas características comunes.

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/pydatajson#60]
Según explica @fapetrone:

> Me pasó validando energía de obtener el siguiente error. Esto está pasando para no menos de 10 URLs de energia.
Creo que es el espacio de la URL que genera el siguiente reporte

```python
{u'error_code': 2,
      u'instance': u'http://www.energia.gob.ar/contenidos/archivos/Reorganizacion/informacion_del_mercado/publicaciones/energia_en_gral/balances_2016/balances/BEN 2015_final.xlsx',
      u'message': "u'http://www.energia.gob.ar/contenidos/archivos/Reorganizacion/informacion_del_mercado/publicaciones/energia_en_gral/balances_2016/balances/BEN 2015_final.xlsx' is not a u'uri'",
      u'path': [u'dataset', 8, u'distribution', 0, u'downloadURL'],
      u'validator': u'format',
      u'validator_value': u'uri'},
```

Deberíamos:

1. Investigar brevemente si existe en la definición de URL/URI alguna restricción a la presencia de espacios en blanco en ellas.
2. En caso de existir dicha restricción,
  -  mantener el comportamiento actual del validador, y
  -  considerar si `ckan_reader.read_ckan_catalog` debería transformar "silenciosamente" los espacios en blanco encontrados a "%20".
3. En caso de no existir la restricción:
  - mantener el comportamiento de `read_ckan_catalog`, y 
  - considerar qúe modificaciones (además de esta, necesariamente) al validador de URIs queremos realizar, e implementarlas.

Estimo la investigación sobre este tema en 2 horas. La duración del desarrollo de la funcionalidad dependerá del resultado de la investigación.

**Comment by abenassi** [comment]
@capitantoto lo tomás en algún momento del día de mañana que te parezca adecuado? Si hoy estás libre o quemado en algún momento y querés cambiar, tmb podría ser hoy.

**Comment by capitantoto** [comment]
Luego de una breve investigación, pareciera ser que sí, es obligatorio codificar los espacios segun RFCs

## RFC 1738 (1994):
https://www.ietf.org/rfc/rfc1738.txt
>Unsafe:
  Characters can be unsafe for a number of reasons.  *The space
  character is unsafe because significant spaces may disappear and
  insignificant spaces may be introduced when URLs are transcribed or
  typeset or subjected to the treatment of word-processing programs.*
  The characters "<" and ">" are unsafe because they are used as the
  delimiters around URLs in free text; the quote mark (""") is used to
  delimit URLs in some systems.  The character "#" is unsafe and should
  always be encoded because it is used in World Wide Web and in other
  systems to delimit a URL from a fragment/anchor identifier that might
  follow it.  The character "%" is unsafe because it is used for
  encodings of other characters.  Other characters are unsafe because
  gateways and other transport agents are known to sometimes modify
  such characters. These characters are "{", "}", "|", "\", "^", "~",
  "[", "]", and "`".   All unsafe characters must always be encoded within a URL. For
  example, the character "#" must be encoded within URLs even in
  systems that do not normally deal with fragment or anchor
  identifiers, so that if the URL is copied into another system that
  does use them, it will not be necessary to change the URL encoding.

## RFC 3986 (2005)
Definitivamente los espacios en blanco no son parte de una URL válida. No figuran en la notación regular del Apéndice A, y se sugiere eliminarlos de todo input de usuarios:
http://www.ietf.org/rfc/rfc3986.txt

>In practice, URIs are delimited in a variety of ways, but usually within double-quotes "http://example.com/", angle brackets <http://example.com/>, or just by using whitespace. These wrappers do not form part of the URI.
[...]
In some cases, extra whitespace (spaces, line-breaks, tabs, etc.) may have to be added to break a long URI across lines.  The whitespace should be ignored when the URI is extracted.
[...]
For robustness, software that accepts user-typed URI should attempt to recognize and strip both delimiters and embedded whitespace.

## Curso de acción sugerido
Según lo acordado con @beni por Slack, haremos que
* DataJson.validate_catalog siga marcando como inválidas las URLs con espacios, pero sugiera la corrección por %20.
* readers.read_ckan_catalog emita una advertencia cuando encuentre una URL con espacios en blanco, e incondicionalmente los reemplace por %20.

**Comment by capitantoto** [comment]
@abenassi podemos cerrar este issue bajo el resultado "no se realizará ninguna modificación?"

**Comment by abenassi** [comment]
Si, señor. Este tema esta definido ya.

**Comment by capitantoto** [comment]
Cierro.
