### ISSUE TITLE
Modificar `readers.read_catalog` para que la deducción del formato a partir del sufijo del archivo o URL a validar sea más robusta.

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/pydatajson#61]
Como comentó @nsampi en el canal de pydatajson:

> chicos les sumo un dato que nos esta pasando un usuario de pydatajson
http://ciudadabierta.site.staging.junar.com/data.json/
ahí tenemos un ejemplo
tuve que tocar el validador
porque nosotros obligamos a poner un / al final
entonces, lo consideraba al formato como "json/" 

La solución más sencilla consiste en quitarle el caracter "/" al sufijo deducido de la URL o dirección de archivo provista.

**Comment by capitantoto** [comment]
@abenassi creo que con esta modificación mínima (#62) estamos cubiertos. ¿Querríamos algo más "robusto" o esto nos conforma?

**Comment by abenassi** [comment]
mergeado el PR! Con esto me parece que estamos bien por ahora
