### ISSUE TITLE
Los cálculos de indicadores deberían ser a prueba de datasets con metadata errónea

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#63]
```https://raw.githubusercontent.com/datosgobar/libreria-catalogos/master/energia/data.json```

En el data.json de Energía hay algún dataset que no tiene `accrualPeriodicity`. Este es un dataset de "metadata errónea" que debería figurar en el conteo del indicador de cantidad de datasets con metadata errónea.

El cálculo de los indicadores que dependen de metadata de datasets, no debería romperse por errores en la metadata de un dataset. Este error debería atraparse con un `try: except:` y seguir calculando el indicador sin contar ese dataset. En el caso actual, con que haya un sólo dataset de metadata errónea se anula todo el cálculo de indicadores del catálogo.

<img width="1284" alt="screenshot 2017-05-11 23 08 08" src="https://cloud.githubusercontent.com/assets/4405346/25979472/058c7256-369f-11e7-909a-35004440b911.png">

**Comment by lucaslavandeira** [comment]
1.
