### ISSUE TITLE
Spike: investigar la dificultad de agregar validaciones para theme

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#68]
`pydatajson` no chequea que un `theme` esté dentro de la `themeTaxonomy` declarada en la metadata del catálogo.

Tampoco chequea que un `superTheme` esté dentro de la `superThemeTaxonomy`.

Estimar la complejidad de estas dos validaciones

**Comment by capitantoto** [comment]
Este Issue quedará reservado para investigar formas de validar los valores de "theme" dados a cierto dataset.

La validación de superTheme se trabajará directamente en https://github.com/datosgobar/pydatajson/issues/73.

**Comment by abenassi** [comment]
Se incorporó una sección de validaciones en python para suplir las necesidades de validaciones que no se puede definir fácilmente en JSON Schema.

Para las nuevas validaciones se prefiere siempre su definición en JSON Schema, y se acepta su definición en python cuando esto parece imposible, muy difícil, impráctico o poco claro.
