### ISSUE TITLE
Escribir tests para validación de tipos básicos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#7]

**Comment by capitantoto** [comment]
Estoy trabajando en esto. En la branch de desarrollo 0.1.1 (https://github.com/datosgobar/pydatajson/tree/0.1.1), los esquemas de validación tiene los tipos básicos para todos los campos, obligatorios, recomendados y opcionales. Todavía no se ha incluido la posibilidad de que un campo obtativo tome un valor nulo.

**Comment by capitantoto** [comment]
Algunos asuntos a tratar hoy:
* Estructura de tests actuales:
  * arranco siendo tests de presencia de campos requeridos, ahora qué son?
  * tansformarlos en tests de integracion (diferencias entre unit test e integration test?), y probar is_valid y validate contra cada data.json (idealmente, en un único test para ambas funciones?)
* Testeo de tipos de campos:
  * hacerlo o no?: concretamente, que el validador encuentre errores cuando el tipo de un campo no es el esperado, es deber de jsonschema, no de pydatajson: tiene sentido repetir tests? tal vez testear unicamente los tipos mixtos/nulificables? ademas: los testeamos a nivel data.json completo, o con microesquemas?
  * como hacerlo?: actualmente is_valid/validate reciben una URL o un path, NO un diccionario. ergo, como hacemos para cambiar de a una clave del diccionario y testear la respuesta? tiene sentido exponer un atributo DataJson.instance/datajson_dict/otro que se peuda modificar y volver a validar? Que valor tomaría (el de la última instancia validada por default, imagino)? Tiene sentido empezar a separar validadores de catalogo/dataset/distribucion?
* Revision de decisiones de diseño:
  * realmente vale la pena aceptar null values en algunos campos? En que campos exactamente?
 * Bug incomprensible: dataset_result() falla cuando un campo tiene un entero o nulo

**Comment by capitantoto** [comment]
Oh sí, los tests están escritos, y pasan! (excepto por los puntos donde se rompe ErrorTree como mencionamos ayer). Se pueden chusmear en test/test_pydatajson.py , debajo del inline comment `# Tests de campos requeridos`([link](https://github.com/datosgobar/pydatajson/blob/0.1.1/tests/test_pydatajson.py#L76))
