### ISSUE TITLE
validate_catalog debe ser capaz de devolver la lista de errores encontrados en el catálogo en formato tabla.

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/pydatajson#74]
Dicha tabla deberá incluir exactamente la misma información que el diccionario de la respuesta actual. La diferencia consistirá en que el resultado será una lista de diccionarios, que se pueda exportar como tabla utilizando el método `pydatajson.writers.write_table`.

**Comment by abenassi** [comment]
Resuelto
