### ISSUE TITLE
DataJson._datasets_equal(dataset, other) no compara correctamente claves simples 

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/pydatajson#77]
La función `DataJson._datasets_equal` (líneas 957 a 988 de `pydatajson/core.py` no compara correctamente los campos "title", "accrualPeriodicity" e "issued":

```
(...)
        for field in fields:
            if isinstance(field, list):
                value = helpers.traverse_dict(dataset, field)
                other_value = helpers.traverse_dict(other, field)
            else:
                value = dataset.get(field)
                other_value = dataset.get(field) <<< AQUÍ DEBERÍA DECIR "other.get(field)"

            if value != other_value:
                return False
```

Entiendo que el error es un simple "typo", y bastaría con hacer el reemplazo sugerido más arriba para solucionarlo.

Para cerrar el ciclo, sería ideal **añadir un test de regresión** que mantenga este bug en línea. Creo que la versión más sencilla, sería una comparación mediante `_datasets_equal` entre dos datasets en que publisher["name"] coincide pero el resto de los campos no. Actualmente, ese test daría True, cuando el resultado esperado debería ser False.

**Comment by capitantoto** [comment]
Lucas, buenos días. Para poder trabajar más tranquilo en la branch `mejoras_datasets_no_federados`, corregí el bug en esa rama. De todas formas, este Issue queda abierto, y consiste básicamente en agregar el test de regresión correspondiente.

**Comment by abenassi** [comment]
@lucaslavandeira esta branch ya está mergeada porque la necesitábamos para otro desarrollo. Te quedaría únicamente agregar el test correspondiente para prevenirnos contra este tipo de error.
Gracias!!
