### ISSUE TITLE
Modificar el schema de validación para que incluya validación de tipos básicos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#8]
* Se define el tipo de todos los campos del perfil de metadatos
* Los nulls debería pasar ok la validación de tipo (si no es un campo requerido/recomendado)

**Comment by capitantoto** [comment]
Estoy trabajando en esto. En la branch de desarrollo 0.1.1 (https://github.com/datosgobar/pydatajson/tree/0.1.1), los esquemas de validación tiene los tipos básicos para todos los campos, obligatorios, recomendados y opcionales. Todavía no se ha incluido la posibilidad de que un campo obtativo tome un valor nulo.

@abenassi podrías darme una información un poco más detallada sobre el asunto de "los campos nulos de CKAN"? Todavía lo tengo muy nebuloso ese asunto.

**Comment by capitantoto** [comment]
Agregué algunos nuevos esquemas de validación:
- `field.json`, para los campos de distribution["field"],
- `theme.json`, para los campos de catalog["themeTaxonomy"] (entiendo que para dataset["theme"] corresponde un array de labels de themes nada mas,**no** el objeto theme entero)
- `mixed-types.json`, donde defino los tipos mixtos `stringOrNull` y `arrayOrNull`, que se usan para validar campos recomendados u opcionales

No me termina de quedar claro si la abstracción de los tipos `stringOrNull` y `arrayOrNull` simplifica o complica la lectura de los esquemas de validación, habrá que revisarlos más adelante.

Con estos cambios, este issue está básicamente cubierto.
