### ISSUE TITLE
Mejorar testing de indicadores de actualización

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/pydatajson#81]
Los indicadores de actualización no son testeados completamente debido a que el estado de un dataset como actualizado o no depende de la fecha en que se ejecute el test. Se debería implementar una solución que haga que las pruebas sean independientes a el día de ejecución.

**Comment by abenassi** [comment]
Cierro temporalmente este issue porque los indicadores de actualización tienen problemas de definición (va a haber que revisarlos completamente).
