### ISSUE TITLE
Soporte para Python3

### ISSUE THREAD

**Issue by lalo73** [datosgobar/pydatajson#87]
¡Hola! Gracias por colaborar con este proyecto. 

Antes de crear el issue, por favor, asegurate de que nadie haya creado el issue que estás reportando.

Si este issue es para pedir nuevas o mejores funcionalidades, contanos:

* ¿Por qué querés esta funcionalidad?

Para actualizar la libreria con soporte a python3, ya que Python2 dejara de tener soporte en 2020

* ¿Cómo esperás que funcione? 

Que pasen todos los tests tanto con Python2 como con Python3

Si querés reportar un bug, especificanos: 

* ¿Cuál es el comportamiento que esperabas y cuál fue el comportamiento recibido? 
* ¿Cuáles son los pasos para reproducir el bug?
* Detalles del contexto: ¿qué sistema operativo, qué versión de navegador estás usando, por ejemplo?
* ¿Tenés algún stack trace o captura de pantalla? Adjuntalo.  

Si tenés otra consulta, dejanos una descripción bien específica, para que podamos ayudarte. 

Para  preguntas de carácter privado, podés escribirnos a datos@modernizacion.gob.ar.

¡Muchas gracias por colaborar!

**Comment by abenassi** [comment]
Mmmm salió con el template completo y todo jajja
