### ISSUE TITLE
Implementar función para cargar un dataset del catálogo a un CKAN / Andino vía API

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#89]
**Contexto**

La federación de datasets consiste en leer la metadata de un dataset de un nodo (que publica un data.json válido) y re-escribirla en otro nodo a través de la API (CKAN / Andino).

La administración ordenada de tareas de federación crónicas de muchos datasets y muchos nodos implica otras funcionalidades más complejas, pero que en última instancia requieren poder automatizar ese paso fundamental.

**Propuesta**

1. Implementar un nuevo módulo en pydatajson con las funcionalidades necesarias para escribir en la API de CKAN *todos los metadatos de un dataset* según el perfil de metadatos v1.1 de la guía (http://paquete-apertura-datos.readthedocs.io/es/stable/guia_metadatos.html#estandar-usado)

2. Integrar el uso de ese módulo en una función _bindeada_ en el objeto `DataJson` del `core.py` de la librería que se llame `push_dataset_to_ckan(dataset_identifier_origin,...)` al que se le pasa el id _original_ (el que usa el nodo original) de un dataset a empujar a un CKAN y escribe los metadatos de ese dataset en el CKAN. (Ver `searchp.py` para ejemplo de cómo tratar el binding de funciones desarrolladas para ser viables en un módulo autónomo).

**Iteraciones de este issue _épico_**

- [x] *Sólo campos que están en CKAN*: la función escribe únicamente aquellos campos de metadatos del dataset y sus distribuciones que existen en la API de CKAN, el resto los ignora. Hasta acá implica resolver el problema de las credenciales, devolver el id del dataset creado, aceptar un id de un dataset que se desea actualizar (en lugar de crear) y por lo demás es un wrapper directo de la API de CKAN.
- [x] *Campos sencillos que no están en CKAN*: aquellos campos de (a) dataset o (b) distribution que no existen en la API de CKAN, pero que no son parte de (c) field. Implica pensar si la resolución más sencilla es utilizando los extras de la API de CKAN o agregar un nuevo endpoint.
- [x] *Campos de `field`, una nueva entidad que no está en CKAN*: Implica pensar si la resolución más sencilla es utilizando nuevamente los extras de la API de CKAN (pasando un JSON donde los keys son los ids de las distribuciones, y los valores son  todo lo que contiene el valor de un `field` en el data.json) o agregar un nuevo endpoint.

**Notas**

+ En la primera versión de esta función, la idea es escribir todos los metadatos tal cual están (_mirror_) en el nuevo CKAN. Más adelante futuras iteraciones **van a introducir operaciones de transformación** sobre los metadatos antes de empujarlos a un nuevo CKAN.

+ El módulo va a requerir pensar una manera transparente y fácil (o más de una) de manejar las **credenciales** necesarias para que pydatajson escriba en un CKAN.

+ Los **campos de metadatos del perfil que no son parte original de CKAN**, van a requerir discusiones para ver cómo aprovechar la API de CKAN y qué desarrollos hacen falta para interpretar esa metadata desde un CKAN Andino o datos.gob.ar, quienes van a poder usar muchos más campos de metadatos que un CKAN común. Cualquier solución tiene que preservar la usabilidad de la nueva función de `pydatajson` para empujar datasets a CKANs _originales_ (desaprovechando toda la metadata que esos CKANs no saben interpretar) a la vez que adopta alguna estrategia para empujar la metadata extra del perfil a un Andino / datos.gob.ar que sepa interpretarla y usarla como está previsto. (_spoiler_: tal vez hay que usar los campos `extra` de un `dataset` en CKAN para esto, y los Andino / datos.gob.ar leen _cierto campo extra con un JSON entero como valor de forma especial_ para parsear los metadatos que necesita /// o tal vez hay una mejor solución).

+ Tal vez no sea posible usar **el _identifier_ original de un dataset** (el que toma la función `push_dataset_to_ckan(dataset_identifier_origin,...)`) para escribir o actualizar el dataset en el nodo federador. En ese caso, habría que elaborar una estrategia sencilla para lidiar con esto, como por ejemplo: que el método `push_dataset_to_ckan` devuelva el _identifier_ generado por el nodo federador (cuando crea un nuevo dataset que no estaba antes) o acepte un argumento opcional `dataset_identifier_destination` para actualizar un dataset ya existente en el nodo federador.

**Entregable**

El nuevo módulo, junto con sus tests asociados (nuevamente ver `search.py` como ejemplo) y la documentación de uso correspondiente en los docs de RTD. La función principal del módulo _bindeada_ en el objeto `DataJson` de `core.py`.

**Comment by abenassi** [comment]
@poligarcia ahí modifiqué el issue agregando iteraciones, avisame si te parece claro (que captura lo que conversamos) o si modificarías las 3 iteraciones.

**Comment by abenassi** [comment]
+ Los ids de los `theme` se pushean a la API en minúsculas siempre

**Comment by pilimayora** [comment]
@lrromero te paso el diccionario hardcodeado que generé en el federar viejo por si te sirve de referencia:

https://github.com/datosgobar/federar/blob/development/src/federar.py#L1022

**Comment by lrromero** [comment]
@abenassi Los ids de recursos se pueden forzar igual que los de package cuando se guardan en ckan. La función guarda el 'id' de recurso igual al 'identifier' de la distribución correspondiente. Lo único  que te hace falta saber es el id del package de ckan al que pertenecen.

**Comment by abenassi** [comment]
@lrromero ok, eso nos deja con que tenemos que tener un patrón de solución
idéntico al que tenemos previsto con el id del dataset.

Si el usuario le pasa a la función un id de destino para cada recurso, la
función debe crear el recurso si el id no existe en CKAN, o pisarlo si el
id ya existe *y pertenece a ese dataset*.

Tener en cuenta:

   - Si ese resource_id (distribution_identifier) de destino existe en CKAN
   pero *no está en ese dataset*, la función debería levantar un error y no
   hacer nada. El usuario pidió realizar una operación inconsistente.
   - Si ese resource_id (distribution_identifier) de destino existe en CKAN
   y* está en ese dataset*, la función debería pisar el recurso. El usuario
   pidió actualizar un recurso existente.
   - Si ese resource_id (distribution_identifier) de destino no existe en
   CKAN, la función debería crear el recurso en ese dataset. El usuario pidió
   crear un recurso nuevo.
   - Si no se provee un resource_id (distribution_identifier) de destino
   para algún recurso, este se crea con el id aleatorio otorgado por CKAN (que
   se va a devolver al usuario en el return value). El usuario pidió crear un
   recurso nuevo sin especificar con qué id lo quiere crear.

En cualquier caso, necesitamos proveer tanto en los argumentos de entrada
como en el return de la función, los mapeos entre ids de origen y destino
de recursos, así como lo pensamos para el id de origen y destino de dataset.
