### ISSUE TITLE
Escribir tests para validación de tipos complejos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/pydatajson#9]
* Ver con @abenassi los casos dudosos de validación de tipos complejos

**Comment by capitantoto** [comment]
Los siguientes casos de testeo, que FALLAN, fueron agregados a la suite:
- una string obligatorio vacía (catalog.description)
- una string opcional vacía (dataset.license)
- un accrualPeriodicity mal formado (sin "/" entre "R" y "P")
- un mail mal formado (con "AT" en lugar de "@")
- una URL mal formada (que no comienza con un esquema como "http://")
- una fecha mal formada (con "/" como separador en lugar de "-")
- una fecha y hora mal formada (sin "T" entre la fecha y la hora)
